<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by www.codechief.org</title>
</head>
<body>
    <h1>{{ $user['name'] }}</h1>
    <p>{{ $user['info'] }}</p>
    <a href="{{ $user['Verification_link']}}">Click here</a>
    <p>Thank you</p>
</body>
</html>


